import { StyleSheet } from 'react-native';

import { colors } from '@/theme/colors';

export const styles = StyleSheet.create({
  root: {
    backgroundColor: '#EEF5F7',
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 22,
  },
  container: {
    alignSelf: 'center',
    maxWidth: 1080,
    width: '100%',
  },
  hero: {
    borderRadius: 28,
    marginBottom: 20,
    minHeight: 250,
    overflow: 'hidden',
    padding: 28,
    position: 'relative',
  },
  heroGlow: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 999,
    height: 260,
    position: 'absolute',
    right: -70,
    top: -90,
    width: 260,
  },
  heroIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.17)',
    borderRadius: 16,
    height: 48,
    justifyContent: 'center',
    marginBottom: 28,
    width: 48,
  },
  heroEyebrow: {
    color: 'rgba(255, 255, 255, 0.78)',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: -0.8,
    marginBottom: 8,
  },
  heroBody: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 16,
    lineHeight: 24,
    maxWidth: 560,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 18,
    marginBottom: 28,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    elevation: 1,
    minWidth: 300,
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
  },
  moodCard: {
    flex: 1.15,
  },
  nextCard: {
    flex: 0.85,
  },
  cardHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  calendarIcon: {
    alignItems: 'center',
    backgroundColor: colors.tipBg,
    borderRadius: 14,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  cardBody: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 20,
  },
  moodOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  moodOption: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: colors.outline,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 6,
    minWidth: 92,
    paddingHorizontal: 10,
    paddingVertical: 14,
  },
  moodOptionSelected: {
    backgroundColor: colors.tipBg,
    borderColor: colors.primary,
    borderWidth: 2,
  },
  moodLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  moodLabelSelected: {
    color: colors.primary,
  },
  feedback: {
    alignItems: 'center',
    backgroundColor: colors.successBg,
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    padding: 12,
  },
  feedbackText: {
    color: colors.success,
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
  },
  loader: {
    marginVertical: 36,
  },
  errorText: {
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    color: colors.error,
    padding: 14,
  },
  nextAppointment: {
    backgroundColor: '#F8FAFC',
    borderColor: colors.outline,
    borderRadius: 18,
    borderWidth: 1,
    padding: 18,
  },
  appointmentTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 5,
  },
  appointmentDate: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textTransform: 'capitalize',
  },
  appointmentDescription: {
    color: colors.textSoft,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 12,
  },
  badges: {
    flexDirection: 'row',
    marginTop: 12,
  },
  badge: {
    alignItems: 'center',
    backgroundColor: colors.tipBg,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  badgeText: {
    color: colors.tipText,
    fontSize: 12,
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 28,
  },
  emptyTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 6,
    marginTop: 12,
  },
  emptyBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  sectionHeader: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  sectionCount: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  questionnaireSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
    maxWidth: 620,
  },
  pendingCount: {
    backgroundColor: '#FFF3D6',
    borderRadius: 999,
    color: '#875B00',
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  questionnaireCard: {
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderRadius: 18,
    borderWidth: 1,
    elevation: 0,
    marginBottom: 10,
  },
  questionnaireRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  questionnaireIcon: {
    alignItems: 'center',
    backgroundColor: '#E7F6FA',
    borderRadius: 14,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  questionnaireInfo: {
    flex: 1,
  },
  questionnaireMeta: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  questionnaireEmptyCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    elevation: 0,
    marginBottom: 22,
  },
  questionnaireFormCard: {
    backgroundColor: colors.surface,
    borderColor: colors.primary,
    borderRadius: 22,
    borderWidth: 1,
    elevation: 1,
    marginBottom: 24,
  },
  questionnaireProgressHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  questionnaireProgressText: {
    flex: 1,
  },
  questionnaireEyebrow: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  questionnaireProgress: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 4,
  },
  progressTrack: {
    backgroundColor: '#DCE8EB',
    borderRadius: 999,
    height: 7,
    marginBottom: 26,
    marginTop: 16,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: '100%',
  },
  questionText: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 30,
    marginBottom: 20,
  },
  answerInput: {
    backgroundColor: colors.surface,
    marginBottom: 20,
  },
  answerOptions: {
    gap: 10,
    marginBottom: 20,
  },
  answerOption: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: colors.outline,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 15,
  },
  answerOptionSelected: {
    backgroundColor: '#E7F6FA',
    borderColor: colors.primary,
    borderWidth: 2,
  },
  answerRadio: {
    borderColor: colors.textMuted,
    borderRadius: 999,
    borderWidth: 2,
    height: 18,
    width: 18,
  },
  answerRadioSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    borderWidth: 5,
  },
  answerOptionText: {
    color: colors.textSecondary,
    flex: 1,
    fontSize: 15,
  },
  answerOptionTextSelected: {
    color: colors.textPrimary,
    fontWeight: '700',
  },
  questionActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  completedHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 10,
  },
  completedTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  completedRow: {
    alignItems: 'center',
    backgroundColor: '#F5FBF8',
    borderRadius: 14,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
    padding: 13,
  },
  completedName: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  completedDate: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  appointmentCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    elevation: 0,
    marginBottom: 12,
  },
  appointmentRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  dateTile: {
    alignItems: 'center',
    backgroundColor: '#E7F6FA',
    borderRadius: 14,
    minWidth: 62,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dateDay: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '800',
  },
  dateMonth: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  appointmentInfo: {
    flex: 1,
  },
  appointmentMeta: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 5,
  },
  privacyNote: {
    alignItems: 'flex-start',
    backgroundColor: '#DFE8EB',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 12,
    marginTop: 18,
    padding: 16,
  },
  privacyText: {
    color: '#52616A',
    flex: 1,
    fontSize: 12,
    lineHeight: 19,
  },
});
