import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#EEF4FB',
  },
  content: {
    paddingHorizontal: 16,
    gap: 20,
  },
  header: {
    gap: 6,
    paddingHorizontal: 4,
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 30,
    fontWeight: '800',
  },
  headerBody: {
    color: '#4B5563',
    fontSize: 15,
    lineHeight: 22,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 18,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  topCard: {
    minHeight: 248,
  },
  cardContent: {
    gap: 24,
  },
  topCardContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  usersCardContent: {
    justifyContent: 'flex-start',
  },
  cardTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '500',
  },
  metricBlock: {
    gap: 10,
  },
  metricValue: {
    color: colors.textPrimary,
    fontSize: 48,
    fontWeight: '800',
  },
  metricCaption: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  chartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  activeUsersChart: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    width: '100%',
  },
  activeUsersBarGroup: {
    alignItems: 'center',
    flex: 1,
    gap: 6,
  },
  activeUsersValueSlot: {
    alignItems: 'center',
    height: 18,
    justifyContent: 'center',
  },
  activeUsersBarTrack: {
    alignItems: 'center',
    height: 72,
    justifyContent: 'flex-end',
    width: '100%',
  },
  activeUsersBar: {
    backgroundColor: '#127680',
    width: '100%',
  },
  chartLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '500',
  },
  chartValue: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  healthTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '500',
  },
  healthTitleGrid: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  healthIndexTotal: {
    color: colors.textSecondary,
    fontSize: 20,
    fontWeight: '300',
  },
  healthIndex: {
    color: colors.primary,
    fontSize: 48,
    fontWeight: '800',
  },
  healthBar: {
    backgroundColor: '#E5E7EB',
    borderRadius: 999,
    height: 12,
    overflow: 'hidden',
    width: '100%',
  },
  healthValueBar: {
    height: '100%',
    width: '84%',
  },
  healthPorcent: {
    alignContent: 'center',
    color: colors.success,
    fontWeight: '700',
  },
  healthBody: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  heartIconBg: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  usersIconBg: {
    alignItems: 'center',
    backgroundColor: '#5AD8F6',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  alertIconBg: {
    alignItems: 'center',
    backgroundColor: '#FFD6D2',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  alertButton: {
    backgroundColor: '#FFD2CD',
    borderRadius: 999,
  },
  alertButtonContent: {
    height: 40,
  },
  alertButtonLabel: {
    color: '#B10F14',
    fontSize: 16,
    fontWeight: '700',
  },
  sentimentCard: {
    backgroundColor: '#F0F4F7',
    borderColor: 'rgba(190, 200, 207, 0.1)',
    borderRadius: 12,
    borderWidth: 1,
    gap: 24,
    padding: 32,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  sentimentHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sentimentHeaderText: {
    flex: 1,
    paddingRight: 16,
  },
  sentimentTitle: {
    color: '#181C1F',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 28,
    maxWidth: 150,
  },
  sentimentSubtitle: {
    color: '#3E484E',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    marginTop: 4,
  },
  sentimentBadge: {
    backgroundColor: '#DFE3E6',
    borderRadius: 9999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  sentimentBadgeText: {
    color: '#3E484E',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  sentimentChartCard: {
    borderBottomColor: 'rgba(190, 200, 207, 0.3)',
    borderBottomWidth: 1,
    height: 264,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingTop: 8,
    position: 'relative',
  },
  sentimentChartInner: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    minHeight: 176,
    width: '100%',
  },
  sentimentGrid: {
    bottom: 36,
    justifyContent: 'space-between',
    left: 8,
    position: 'absolute',
    right: 8,
    top: 8,
  },
  sentimentGridLine: {
    borderBottomColor: 'rgba(190, 200, 207, 0.1)',
    borderBottomWidth: 1,
  },
  sentimentWeekGroup: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-end',
  },
  sentimentBarsGroup: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 3,
    height: 176,
  },
  sentimentBar: {
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    width: 11,
  },
  sentimentWeekLabel: {
    color: '#3E484E',
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 15,
    textAlign: 'center',
    width: '25%',
  },
  sentimentWeeksRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    width: '100%',
  },
  sentimentLegendRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'center',
  },
  sentimentLegendItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  sentimentLegendDot: {
    borderRadius: 9999,
    height: 12,
    width: 12,
  },
  sentimentLegendLabel: {
    color: '#3E484E',
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 15,
  },
  insightsCard: {
    borderRadius: 20,
    gap: 32,
    overflow: 'hidden',
    padding: 32,
    position: 'relative',
  },
  insightsGlow: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 9999,
    height: 128,
    position: 'absolute',
    right: -32,
    top: -32,
    width: 128,
  },
  insightsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  insightsEyebrow: {
    color: '#FFFBFF',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 1.4,
  },
  insightsBody: {
    color: '#FFFBFF',
    fontSize: 18,
    fontWeight: '400',
    lineHeight: 29,
  },
  insightsButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
  },
  insightsButtonContent: {
    height: 44,
  },
  insightsButtonLabel: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  departmentCard: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(190, 200, 207, 0.15)',
    borderRadius: 12,
    borderWidth: 1,
    gap: 24,
    padding: 32,
  },
  departmentTitle: {
    color: '#181C1F',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 28,
    maxWidth: 210,
  },
  departmentList: {
    gap: 24,
  },
  departmentRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  departmentLabel: {
    color: '#3E484E',
    fontSize: 14,
    fontWeight: '700',
    width: 110,
  },
  departmentTrack: {
    backgroundColor: '#E5E9EC',
    borderRadius: 9999,
    flex: 1,
    height: 24,
    overflow: 'hidden',
  },
  departmentFill: {
    backgroundColor: '#1186AC',
    borderRadius: 9999,
    height: '100%',
  },
  departmentValue: {
    color: '#181C1F',
    fontSize: 12,
    fontWeight: '700',
    minWidth: 36,
    textAlign: 'right',
  },
});
