import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    gap: 16,
    paddingHorizontal: 20,
  },
  header: {
    gap: 8,
    paddingHorizontal: 4,
    marginTop: 8,
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 36,
  },
  headerBody: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  aiSessionsCard: {
    backgroundColor: colors.surface,
    borderColor: 'rgba(26, 144, 185, 0.16)',
    borderRadius: 20,
    borderWidth: 1,
    elevation: 2,
    overflow: 'hidden',
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  aiSessionsContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    padding: 18,
  },
  aiSessionsIconBg: {
    alignItems: 'center',
    backgroundColor: colors.iconCircleBg,
    borderRadius: 12,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  aiSessionsInfo: {
    flex: 1,
    gap: 4,
  },
  aiSessionsTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  aiSessionsBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  stateCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    elevation: 2,
    gap: 10,
    padding: 20,
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  stateTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  stateBody: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  retryButton: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primary,
    borderRadius: 999,
    marginTop: 4,
  },
  questionnaireCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderColor: 'transparent',
    borderWidth: 1,
    elevation: 2,
    overflow: 'hidden',
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  questionnaireCardAnswered: {
    backgroundColor: colors.successBg,
    borderColor: colors.success,
  },
  questionnaireContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    padding: 18,
  },
  questionnaireIconBg: {
    alignItems: 'center',
    backgroundColor: colors.iconCircleBg,
    borderRadius: 12,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  questionnaireIconBgAnswered: {
    backgroundColor: colors.surface,
  },
  questionnaireInfo: {
    flex: 1,
    gap: 4,
  },
  questionnaireTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  questionnaireName: {
    color: colors.textPrimary,
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  answeredBadge: {
    backgroundColor: colors.success,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  answeredBadgeText: {
    color: colors.surface,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 14,
  },
  questionnaireMeta: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  answeredMeta: {
    color: colors.success,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
});
