import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: 20,
    gap: 16,
  },
  header: {
    gap: 6,
    paddingHorizontal: 4,
    marginTop: 8,
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 36,
  },
  headerBody: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  createButton: {
    backgroundColor: colors.accent,
    borderRadius: 999,
    alignSelf: 'flex-start',
    marginHorizontal: 4,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  createButtonContent: {
    height: 48,
    paddingHorizontal: 20,
  },
  createButtonLabel: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  statCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 20,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  statCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  statIconBg: {
    alignItems: 'center',
    borderRadius: 10,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  statIconBgBlue: {
    backgroundColor: '#DBEAFE',
  },
  statIconBgPurple: {
    backgroundColor: '#EDE9FE',
  },
  statGrowth: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
  },
  statGrowthText: {
    color: colors.success,
    fontSize: 14,
    fontWeight: '700',
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '400',
    marginBottom: 4,
  },
  statValue: {
    color: colors.textPrimary,
    fontSize: 32,
    fontWeight: '800',
  },
  statCaption: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 4,
  },
  recentCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  recentHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    paddingBottom: 16,
    borderBottomColor: colors.handleIndicator,
    borderBottomWidth: 1,
  },
  recentTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
  },
  recentSeeAll: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  companyItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    padding: 16,
    paddingHorizontal: 20,
    borderBottomColor: colors.handleIndicator,
    borderBottomWidth: 1,
  },
  companyLogo: {
    alignItems: 'center',
    backgroundColor: colors.iconCircleBg,
    borderRadius: 10,
    height: 44,
    justifyContent: 'center',
    width: 44,
    overflow: 'hidden',
  },
  companyLogoImage: {
    width: 44,
    height: 44,
    borderRadius: 10,
  },
  companyInfo: {
    flex: 1,
    gap: 2,
  },
  companyName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '600',
  },
  companyMeta: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  insightsCard: {
    backgroundColor: '#0E7490',
    borderRadius: 20,
    padding: 20,
    gap: 20,
    shadowColor: '#0E7490',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  insightsTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  insightRow: {
    gap: 10,
  },
  insightLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  insightLabel: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 14,
    fontWeight: '400',
  },
  insightValue: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  insightTrack: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 999,
    height: 8,
    overflow: 'hidden',
  },
  insightFill: {
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    height: '100%',
  },
  alertsCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 20,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  alertsTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 16,
  },
  alertItem: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
  },
  alertItemLast: {
    marginBottom: 0,
  },
  alertIcon: {
    marginTop: 2,
  },
  alertContent: {
    flex: 1,
    gap: 2,
  },
  alertTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  alertBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  loadingCenter: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: 14,
    textAlign: 'center',
    padding: 20,
  },
});
